---
title: "Guía de ejercicios Nº1"
output: html_notebook
---

```{r}
#Se cargan las librerías a usar en la resolución de la guía.

library(readxl)
library(ggplot2)

#Se leen los datos de rendimiento académico.

data = read_excel("rendimiento academico.xlsx")
data
```

```{r}
#Se comienza por hacer un análisis exploratorio de la variable "sit_ac", que describe la situación académica de cada alumno.

#Se muestra el resumen clásico de parámetros descriptivos
summary(data$sit_ac)

#Se almacenan los principales parámetros
media_sit_ac = mean(data$sit_ac)
mediana_sit_ac = median(data$sit_ac)
desvio_sit_ac = sd(data$sit_ac)
cuatiles_sit_ac = quantile(data$sit_ac)

#Mediante un histograma se puede visualizar la frecuencia relativa de cada situación académica en la muestra.

ggplot(data = data, aes(data$sit_ac)) +
  geom_histogram(aes(y=(..count..)/sum(..count..)), binwidth = 1, color="black", fill="blue") +
  labs(title="Histograma de frec. rel. de situación académica",x="Situación académica", y = "Frecuencia relativa")

```
```{r}
#Para analizar la influencia del sexo en la muestra, se puede representar la información en un gráfico de caja.

data <- within(data, {
  sexo.cat <- NA
  sexo.cat[sexo == 1] <- "1"
  sexo.cat[sexo == 2] <- "2"
})

ggplot(data=data, aes(y=(..count..)/sum(..count..), x=data$sit_ac, group=data$sexo.cat, fill=data$sexo.cat)) +
  geom_histogram(binwidth=1, color= "black")+
  labs(title="Histograma de frec. rel. de situación académica por sexo",x="Situación académica", y = "Frecuencia relativa", fill="Sexo")
```

